name: CI - Test and Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set environment variables
        run: |
          echo "ORIGIN=http://127.0.0.1:3000" >> .env
          echo "ADMIN_USER=admin" >> .env
          echo "ADMIN_PASSWORD=password" >> .env
          echo "ADMIN_EMAIL=email@example.com" >> .env
          echo "ADMIN_NAME=Administrator" >> .env

      - name: Create Directories
        run: |
          mkdir -p app/prisma/db
          mkdir -p app/uploads/imports
          mkdir -p app/uploads/images

      - name: Build Project
        run: pnpm build

      - name: Start Server in Background
        run: pnpm serve &
        env:
          ORIGIN: http://127.0.0.1:3000

      - name: Wait for Server to be Ready
        run: |
          echo "Waiting for server to be ready..."
          until curl --output /dev/null --silent --head --fail http://127.0.0.1:3000; do
            printf '.'
            sleep 1
          done

      - name: Run Tests
        run: pnpm test

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        if: success()
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jt196/vanilla-cookbook:latest
