name: CI - Test and Build (Stable Release)

on:
  release:
    types: [published]

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml

  docker-build-stable:
    needs: run-tests
    uses: ./.github/workflows/docker-build.yml
    with:
      docker_tags: |
        stable
        type=ref,event=tag
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
