name: Docker Build and Push

on:
  workflow_call:
    inputs:
      docker_tags:
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Debug Secrets Inside Reusable Workflow
        run: |
          echo "Secrets passed: ${{ toJson(secrets) }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jt196/vanilla-cookbook
          tags: ${{ inputs.docker_tags }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
